[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://wavcave-backend.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/admin/login.html"
  status = 302
  conditions = {Host = ["admin.thewavcave.com"]}

[[redirects]]
  from = "/admin"
  to = "/admin/login.html"
  status = 302
  conditions = {Host = ["admin.thewavcave.com"]}

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/rates"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200
  force = true
